export enum Routes {
  AUTH = 'auth',
  AUTH_GOOGLE = 'auth/google',
  USERS = 'users',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  SESSION = 'SESSION_SERVICE',
  MAILER = 'MAILER_SERVICE',
  MAILS = 'MAILS_SERVICE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD_SERVICE',
  AUTH_GOOGLE = 'AUTH_GOOGLE_SERVICE',
}
